Revert "Unfound code sniffer warns instead of fails"
This reverts commit 1321b7db48b3284287196624358c6c03f7d0bba5.

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -6,8 +6,8 @@ PHPCS_BIN=vendor/bin/phpcs
 
 if [ ! -f $PHPCS_BIN ];
   then
-    echo "WARNING: PHP Code Sniffer was not found where we thought it should be. This commit may contain coding violations. "
-    exit 0
+    echo "PHP Code Sniffer was not found in this project's bin directory. Please run composer install. "
+    exit 1
 fi
 
 echo "Sniffing staged files via PHP Code Sniffer..."
